import {readFile} from 'node:fs/promises';
import path from 'node:path';
import {ROOT} from './lib.mjs';
export const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const origin=new URL(process.env.PUBLIC_ORIGIN||`http://127.0.0.1:${process.env.PORT||4178}`).origin;
export const isPublic=origin.startsWith('https://');
const email=process.env.CONTACT_EMAIL, copyrightEmail=process.env.COPYRIGHT_EMAIL, operator=process.env.OPERATOR_NAME;
const contactLink=(value,fallback)=>value&&/^[^\s@<>]+@[^\s@<>]+\.[^\s@<>]+$/.test(value)?`<a href="mailto:${escape(value)}">${escape(value)}</a>`:`<code>${escape(fallback)}</code> (not configured)`;
const contact=contactLink(email,'hello@[DOMAIN]'), copyright=contactLink(copyrightEmail,'copyright@[DOMAIN]');
export const disclaimer='Reel Fetch is an independent service and is not affiliated with, endorsed by, sponsored by, or associated with Instagram or Meta Platforms, Inc. Instagram and related trademarks belong to their respective owners.';
const brand='<a class="brand" href="/" aria-label="Reel Fetch home"><img src="/favicon.svg" width="31" height="31" alt="">Reel Fetch</a>';
export const header=`<header class="topbar">${brand}<nav class="nav" aria-label="Main navigation"><a href="/#download">Download</a><a href="/#how-it-works">How It Works</a><a href="/#faq">FAQ</a></nav></header>`;
export const footer=`<footer class="footer"><div class="footer-inner"><div class="footer-top">${brand}<nav class="footer-links" aria-label="Policies and contact"><a href="/terms">Terms</a><a href="/privacy">Privacy</a><a href="/copyright">Copyright</a><a href="/contact">Contact</a><a href="/disclaimer">Disclaimer</a></nav></div><div class="footer-note"><span>© 2026 Reel Fetch</span><p>${disclaimer}</p></div></div></footer>`;
const setup=(!email||!copyrightEmail||!operator)?'<p class="setup-note">Local preview: these policies describe this version of the app. The service operator, working contact addresses, and jurisdiction-specific requirements must be finalized before public launch.</p>':'';
const section=(title,text)=>`<section><h2>${title}</h2>${text}</section>`;
const p=text=>`<p>${text}</p>`;
export const pages={
 '/terms':{title:'Terms of Service',description:'Read the permitted uses, limits, and responsibilities for using Reel Fetch.',content:
 p(`These terms govern your use of Reel Fetch, operated by ${escape(operator||'[OPERATOR NAME — not configured]')}. By using the service, you agree to these terms. If you do not agree, do not use the service.`)+
 section('Eligibility',p('You must be at least 18 or the age of legal majority where you live. If you use Reel Fetch for an organization, you must have authority to accept these terms on its behalf.'))+
 section('What the service does',p('Reel Fetch attempts to retrieve eligible public Instagram videos through its supported access method and prepare available video or audio formats. Availability is not guaranteed. A successful technical response does not establish that a download or later use is lawful, licensed, or permitted by a platform.'))+
 section('Permitted use and your responsibilities',p('Submit only URLs for content you own, are authorized to download, or are otherwise legally entitled to save. You are responsible for the submitted URL, the content, your permission, and subsequent use. Check rights covering audio, images, performances, and other included material, as well as applicable platform terms. Downloading does not transfer copyright or grant permission to repost, distribute, or monetize the content.'))+
 section('Prohibited use','<ul><li>Knowingly infringing copyright, privacy, or other rights, or downloading without required authorization.</li><li>Accessing private accounts, bypassing login or access controls, defeating DRM, or circumventing technological protections.</li><li>Submitting malicious links, exploiting the service, disrupting others, or using it for fraud, harassment, or unlawful purposes.</li><li>Automated abuse, excessive requests, evading rate limits, or attempting to access arbitrary internal or external network resources.</li><li>Misrepresenting a relationship with Instagram, Meta, or the content owner.</li></ul>')+
 section('Availability and limits',p('The service may reject unsupported links, limit file sizes or duration, queue requests, enforce rate limits, or become unavailable. Public content may be restricted, deleted, or blocked by its platform. Reel Fetch does not offer account-login or restriction-bypass features. We may change, suspend, or discontinue features, and restrict access in response to misuse or security concerns.'))+
 section('Third-party platforms and intellectual property',p('Third-party platforms control their content and access rules. Their terms and policies may apply separately. Reel Fetch is not responsible for their availability or changes and does not grant rights to their trademarks or media. Our name, design, and software remain subject to their applicable ownership and licenses.'))+
 section('Copyright reports and repeated abuse',p('Rights holders can report alleged infringement using our <a href="/copyright">Copyright Policy</a>. We may investigate, remove temporary files under our control, block specific source URLs, or restrict repeated misuse where technically feasible. The absence of user accounts can limit our ability to identify a repeat user.'))+
 section('Warranties and liability',p('The service is provided on an “as available” basis. To the extent permitted by applicable law, we do not warrant continuous availability, accuracy, security, fitness for a particular purpose, or successful downloads. To that same extent, we are not liable for indirect or consequential losses caused by use of or inability to use the service. Nothing in these terms excludes liability or consumer rights that cannot lawfully be excluded.'))+
 section('Responsibility for claims',p('You are responsible for losses or claims caused by your unlawful use or violation of others’ rights to the extent provided by applicable law. These terms do not impose an unlimited consumer indemnity or waive protections that apply to you.'))+
 section('Changes and access restrictions',p('We may update the service or these terms. Updated terms will show a revised effective date; material changes will be identified on this page. If you do not accept a change, stop using the service. We may restrict or end access when reasonably necessary for abuse prevention, legal obligations, or operation of the service.'))+
 section('Contact',p(`Questions about these terms: ${contact}. No working contact address is implied by a placeholder.`))},
 '/privacy':{title:'Privacy Policy',description:'How Reel Fetch processes links and temporary media, with minimal data collection.',content:
 p(`This policy describes the current Reel Fetch application. Its operator is ${escape(operator||'[OPERATOR NAME — not configured]')}. ${escape(process.env.HOSTING_DESCRIPTION||'This local preview runs on your computer; public hosting is not configured.')}`)+
 section('Data used to process a request',p('When you submit a link, the app validates it and removes query parameters such as sharing or tracking codes. It temporarily holds the normalized URL, returned media title and creator label, format information, processing status, and a random download identifier in server memory. It retrieves media only to prepare the requested preview or download.'))+
 section('No Instagram credentials or user accounts',p('The application does not have user accounts and does not ask for or store Instagram passwords, session cookies, or login credentials. A rights confirmation is sent with a download request and is used to validate that request; it is not stored as a separate user profile.'))+
 section('Network information and logs',p('HTTP requests inherently expose connection information, such as an IP address and browser headers, to the receiving server. This application does not keep access logs or log submitted URLs. For abuse prevention, its rate limiter holds client IP addresses and request counts in server memory for up to 61 seconds; they are not saved to disk. The hosting provider, operating system, or a reverse proxy may separately keep technical logs, as described in the hosting information above.'))+
 section('Temporary files and retention',p('Source files are temporarily reused to speed up additional format choices. Sources and session metadata expire 30 minutes after the latest processing attempt completes. Failed output folders are removed. Finished downloads expire 30 minutes after preparation completes. Resolved link metadata is also cached separately for 90 seconds. Cleanup runs every minute while the app is running, so removal can take up to one additional minute. If the server stops unexpectedly, temporary files remain on its disk until cleanup runs after restart. In-memory metadata is lost on restart. Files saved by your browser remain on your device until you delete them.'))+
 section('Cookies, analytics, and advertising',p('This version sets no cookies and uses no analytics, advertising scripts, tracking pixels, or browser storage. Fonts and interface assets are served with the app. Browser caching is controlled with response headers. Empty, hidden advertisement slots exist in the layout, but no ads or advertising data collection are enabled. If these practices change, this policy and any required consent controls must be updated before the change takes effect.'))+
 section('Third parties',p('The server contacts Instagram and its media delivery domains to resolve and retrieve a submitted video. Those services receive the server’s connection information and the requests needed to retrieve the content; their own policies apply. There is no separate commercial downloader API in this version. No personal information is sold or shared with advertising networks by this application. No searchable public archive of downloaded content is created.'))+
 section('Purpose and legal basis',p('Request data is used to deliver the requested function, maintain security, and prevent abuse. Where data-protection law applies, the operator must identify the applicable legal basis, such as delivering a requested service or a legitimate security interest, and provide any additional required notice before public launch.'))+
 section('Security',p('The app restricts supported URLs, validates server requests, limits request sizes and concurrency, uses random file identifiers, and expires temporary data. Local operation binds to your computer by default. Production operation requires a configured HTTPS origin and an appropriate reverse proxy. No system is completely secure; do not submit private or sensitive links.'))+
 section('Your choices and rights',p(`You can stop a request or stop using the service. Depending on where you live, you may have rights to access, correct, delete, restrict, or object to the processing of personal data, request portability, or complain to a supervisory authority. Contact ${contact} with enough information to identify your request. Because this version has no user accounts and keeps little data, the operator may be unable to associate a request with a particular person. Avoid including unnecessary sensitive information.`))+
 section('Children and international users',p('Reel Fetch is intended for adults and is not directed to children. Do not use it if you do not meet the eligibility requirements. Processing occurs on the server described above; Instagram requests may involve international infrastructure. The operator must describe any additional international-transfer safeguards required for its deployment.'))+
 section('Updates and contact',p(`Changes will be posted here with a revised effective date. Privacy questions: ${contact}. The address must be configured before a public launch.`))},
 '/copyright':{title:'Copyright Policy',description:'Our copyright responsibilities and how rights holders can report alleged infringement.',content:
 p('Reel Fetch respects intellectual-property rights. Do not use the service to knowingly infringe copyright. Public availability does not establish permission to download, reuse, or redistribute a work. Users must have the necessary rights for both video and audio.')+
 section('Report alleged infringement',p(`If you own a copyrighted work or are authorized to act for the owner, send a report to ${copyright}. The placeholder is not an active mailbox. Please include:`)+'<ol><li>Identification of the copyrighted work, or a representative list if several works are involved.</li><li>Identification of the allegedly infringing material and enough information to locate it in this service, including relevant source URLs or download identifiers. Do not attach unnecessary copies of the material.</li><li>Your name, organization if applicable, mailing address, telephone number, and email address.</li><li>A statement that you have a good-faith belief that the use is not authorized by the rights holder, its agent, or applicable law.</li><li>A statement that the information is accurate and, under penalty of perjury where applicable, that you are the rights holder or are authorized to act on its behalf.</li><li>Your physical or electronic signature.</li></ol>')+
 section('What happens next',p('The operator will review sufficiently detailed reports and may request clarification, remove temporary files under its control, or restrict access to particular URLs. Reports should concern use involving Reel Fetch; the operator cannot remove the original post from Instagram or files already saved on another person’s device. Those issues should be directed to the relevant platform or party.'))+
 section('Accuracy, responses, and repeated abuse',p(`Do not submit knowingly false claims. If you believe a restriction is mistaken, explain why and provide relevant supporting information to ${copyright}. The operator will assess the circumstances and applicable law. Repeated substantiated abuse may result in continued URL blocks or access restrictions where technically feasible. Because the app has no accounts and does not retain identifying access logs, identifying repeat users may be limited.`))+
 section('No claim of statutory safe-harbor status',p('This reporting process does not by itself establish eligibility for a legal safe harbor or constitute registration of a designated agent. Any required agent designation, notice process, or counter-notice procedure must be established by the operator for the jurisdiction and service it actually operates. See the <a href="https://www.copyright.gov/512/" rel="noreferrer">U.S. Copyright Office’s information about Section 512</a>.'))},
 '/contact':{title:'Contact',description:'Get help with Reel Fetch or find the right contact for a copyright or privacy question.',content:
 p('For a failed download, first check that the URL points to a public video and that you have permission to save it. Instagram restrictions can prevent retrieval even when a post is publicly visible.')+
 `<div class="contact-card"><h2>General questions & privacy</h2>${p(contact)}<h2>Copyright reports</h2>${p(copyright)}${p('Please follow the <a href="/copyright">copyright reporting instructions</a> so the operator has enough information to review your report.')}</div>`+
 section('What to include',p('Describe the issue, the approximate time it happened, and the message displayed. Include a source URL only if necessary and safe to share. Never send an Instagram password, authentication cookie, or private account content. This page does not contain a submission form or send messages.'))},
 '/disclaimer':{title:'Service Disclaimer',description:'Independent service, content eligibility, and technical limits of Reel Fetch.',content:
 section('Independent service',p(disclaimer))+
 section('Content rights and platform rules',p('Reel Fetch cannot determine all rights, licenses, or legal exceptions that apply to a video, soundtrack, user, or location. Successful access is not proof of permission. Use only content that you may lawfully access and download through the supported method, and comply with applicable laws and platform rules.'))+
 section('Technical limits',p('Reel Fetch does not use account credentials or bypass private-account restrictions, login requirements, DRM, or other access controls. If access is denied, the request fails. Availability and quality depend on what the source provides. Audio may be absent. The service does not upscale video or remove marks already present.'))+
 section('No legal certification',p('A disclaimer or confirmation checkbox cannot make an otherwise unauthorized download lawful. These policies describe intended use and product behavior; they are not a guarantee of legal compliance in every jurisdiction.'))}
};
export function metadata(route,title,description){const url=origin+route;return `<meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(title)}${route==='/'?'':' | Reel Fetch'}</title><meta name="description" content="${escape(description)}"><meta name="theme-color" content="#ffffff"><meta name="robots" content="${isPublic?'index, follow':'noindex, nofollow'}"><link rel="canonical" href="${escape(url)}"><meta property="og:type" content="website"><meta property="og:site_name" content="Reel Fetch"><meta property="og:title" content="${escape(title)}"><meta property="og:description" content="${escape(description)}"><meta property="og:url" content="${escape(url)}"><meta name="twitter:card" content="summary">`;}
export async function render(route){
 if(route==='/')return(await readFile(path.join(ROOT,'public/home.html'),'utf8')).replace('<!--META-->',metadata('/','Reel Fetch — Download Reels. Fast. Simple.','Preview and download eligible public Instagram Reels in the best available quality, or save their audio. No account needed.')).replace('<!--HEADER-->',header).replace('<!--FOOTER-->',footer);
 const page=pages[route];if(!page)return null;
 return`<!doctype html><html lang="en"><head>${metadata(route,page.title,page.description)}<link rel="icon" href="/favicon.svg"><link rel="stylesheet" href="/style.css"></head><body><a class="skip-link" href="#content">Skip to content</a>${header}<main class="legal-main" id="content"><a class="back" href="/">← Back to Reel Fetch</a><h1>${page.title}</h1><p class="updated">Last updated September 25, 2026</p>${setup}${page.content}</main>${footer}</body></html>`;
}
export function sitemap(){return`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${['/',...Object.keys(pages)].map(r=>`<url><loc>${escape(origin+r)}</loc></url>`).join('')}</urlset>`;}
export function robots(){return isPublic?`User-agent: *\nDisallow: /api/\nSitemap: ${origin}/sitemap.xml\n`:'User-agent: *\nDisallow: /\n';}


